/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package System;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.Random;
import javax.swing.JPanel;

import java.awt.Graphics;  

import java.awt.*;
import java.awt.event.*;
import javax.swing.JOptionPane;
/**
 *
 * @author thead
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        
        
        Random rand = new Random(); //instance of random class

    
 //CHANGE HERE********************************//    
      int upperboundn = 250; int upperboundm=10000;
//CHANGE HERE********************************//    
      int int_random;
         float double_random;
 Connection conobj ; 
   Statement statobj ;
 ResultSet  resobj; 
   int number;

       String time;

         /**    
      TL01-1 02-2 03-3 04-4
      11-5 12-6 13-7 14-8
      21-9 22-10 23-11 24-12
      * */
      
  //CHANGE HERE********************************//      
        String query="create table TL24(TL24 INT PRIMARY KEY, NTU_VALUES FLOAT ,MQ2_VALUES INT, TIME CHAR(30))";
    //CHANGE HERE********************************//    
        
        
        String loc= "jdbc:derby://localhost:1527/Toilet";
        String user="Group_17";
        String pass="123";

        try {

            conobj=DriverManager.getConnection(loc, user, pass);
            statobj=conobj.createStatement();

  
 statobj.execute(query);
             
          for(int i=0;i<24;i++){
             
             number=i+1;
              int_random = rand.nextInt(upperboundn); 
       double_random=rand.nextFloat();
      float n=int_random+double_random;
                       
      int_random = rand.nextInt(upperboundm); 
    double_random=rand.nextFloat();
     int m=int_random;
     
     
        
      
      //CHANGE HERE****************************//  
             time="oo";
                    

        //CHANGE HERE****************************//               
                               
                     
   //CHANGE HERE****************************//  
   query="insert into TL24 values("+number+","+n+","+m+",'"+time+"')";
   //CHANGE HERE********************************//    
   
      statobj.execute(query);

        }
        
        }
        catch (SQLException e){
            e.printStackTrace();
        }  
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1298, 767));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

}
